services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: nest-crud
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=99tech
    ports:
      - 3000:3000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.29
    container_name: mysql-99tech
    restart: unless-stopped # Restart policy to keep the container running
    environment:
      - MYSQL_DATABASE=99tech # Create a database named 99tech
      - MYSQL_ROOT_PASSWORD=123456 # Set the MySQL root password
    volumes:
      - ./mysql/data:/var/lib/mysql # Persist MySQL data
      - ./mysql/sql:/docker-entrypoint-initdb.d # Mount the SQL script to initialize the database
    ports:
      - 3306:3306
